CREATE TABLE DATA1
(
	DISTRICT VARCHAR(250),
	STATE VARCHAR(250),
	GROWTH FLOAT,
	SEX_RATIO,
	LITERACH FLOAT
);

SELECT * FROM DATA1;

COPY DATA1 FROM 'J:\Portfolio Project\Indian Census\data\\Dataset1.CSV' DELIMITER ',' CSV HEADER;

SELECT * FROM DATA1;

CREATE TABLE DATA2
(
	DISTRICT VARCHAR(250),
	STATE VARCHAR(250),
	AREA_KM2 INT,
	POPULATION INT
);

SELECT * FROM DATA2;

COPY DATA2 FROM 'J:\Portfolio Project\Indian Census\data\\Dataset2.CSV' DELIMITER ',' CSV HEADER;

SELECT * FROM DATA2;


